version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200 > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  db:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=eschecker
      - POSTGRES_USER=kaeunlee
      - POSTGRES_PASSWORD=qwer1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaeunlee -d eschecker"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # 로컬 Django가 DB 접속할 수 있도록 열어줘야 함

volumes:
  pgdata:
