
version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es-local
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # x-pack 보안 기능 끄기
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # elasticsearch jvm 힙 메모리 초기/최대 고정
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7
    container_name: es-redis
    ports:
      - "6379:6379"

  web:
    build: ./app
    container_name: es-checker-web
    environment:
      - DJANGO_DEBUG=1
      - TZ=Asia/Seoul
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=checks-*
      - DEMO_MODE=true
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app/eschecker:/code/eschecker
      - ./app/checks:/code/checks
      - ./app/manage.py:/code/manage.py
      - ./app/static:/code/static
      - ./app/templates:/code/templates
    ports:
      - "8000:8000"
    command: ["bash", "/code/start.sh"]

  celery_worker:
    build: ./app
    container_name: es-checker-celery
    environment:
      - DJANGO_DEBUG=1
      - TZ=Asia/Seoul
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=checks-*
      - DEMO_MODE=true
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - web
    volumes:
      - ./app/eschecker:/code/eschecker
      - ./app/checks:/code/checks
      - ./app/manage.py:/code/manage.py
      - ./app/static:/code/static
      - ./app/templates:/code/templates
    command: ["bash", "/code/start_celery_worker.sh"]

  celery_beat:
    build: ./app
    container_name: es-checker-beat
    environment:
      - DJANGO_DEBUG=1
      - TZ=Asia/Seoul
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=checks-*
      - DEMO_MODE=true
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - web
    volumes:
      - ./app/eschecker:/code/eschecker
      - ./app/checks:/code/checks
      - ./app/manage.py:/code/manage.py
      - ./app/static:/code/static
      - ./app/templates:/code/templates
    command: ["bash", "/code/start_celery_beat.sh"]
