# Generated by Django 5.0.6 on 2025-08-29 11:08

import mail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expired_at',
            field=models.DateTimeField(default=mail.models.get_expired_at),
        ),
    ]
