# Generated by Django 5.0.6 on 2025-08-13 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('item', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=45)),
                ('switch_su', models.CharField(max_length=100)),
                ('sftp_file', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('appeal_done', models.BooleanField(default=False)),
                ('status', models.CharField(default='미입력', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_key', models.CharField(db_index=True, max_length=100)),
            ],
        ),
    ]
