# Generated by Django 5.0.6 on 2025-08-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='checkrecord',
            name='time',
            field=models.TimeField(),
        ),
    ]
